In [1]:
import re
import numpy as np
from PIL import Image
print("Huffman Compression Program")
print("---------------------------------------------------")

file = input("Enter the filename:")
my_string = np.asarray(Image.open(file),np.uint8)
shape = my_string.shape
a = my_string
print ("Entered string is:",my_string)
my_string = str(my_string.tolist())


Huffman Compression Program
---------------------------------------------------
Entered string is: [[  0   1   0 ...   0   0   1]
 [  2  85 124 ... 101  68   0]
 [  0 120 176 ... 114  47   0]
 ...
 [  0  42  64 ...  64  43   0]
 [  1  29  43 ...  42  35   0]
 [  0   0   1 ...   0   1   0]]


In [2]:
letters = []
only_letters = []
for letter in my_string:
    if letter not in letters:
        frequency = my_string.count(letter)             #frequency of each letter repetition
        letters.append(frequency)
        letters.append(letter)
        only_letters.append(letter)

In [3]:
nodes = []
while len(letters) > 0:
    nodes.append(letters[0:2])
    letters = letters[2:]                               # sorting according to frequency
nodes.sort()
huffman_tree = []
huffman_tree.append(nodes)                             #Make each unique character as a leaf node

In [4]:
def combine_nodes(nodes):
    pos = 0
    newnode = []
    if len(nodes) > 1:
        nodes.sort()
        nodes[pos].append("1")                       # assigning values 1 and 0
        nodes[pos+1].append("0")
        combined_node1 = (nodes[pos] [0] + nodes[pos+1] [0])
        combined_node2 = (nodes[pos] [1] + nodes[pos+1] [1])  # combining the nodes to generate pathways
        newnode.append(combined_node1)
        newnode.append(combined_node2)
        newnodes=[]
        newnodes.append(newnode)
        newnodes = newnodes + nodes[2:]
        nodes = newnodes
        huffman_tree.append(nodes)
        combine_nodes(nodes)
    return huffman_tree                                     # huffman tree generation

In [5]:
newnodes = combine_nodes(nodes)

huffman_tree.sort(reverse = True)


checklist = []
for level in huffman_tree:
    for node in level:
        if node not in checklist:
            checklist.append(node)
        else:
            level.remove(node)
count = 0
for level in huffman_tree:
    print("Level", count,":",level)             #print huffman tree
    count+=1
print()

Level 0 : [[76049, ' ,425[]8317960']]
Level 1 : [[32766, ' ,', '1'], [43283, '425[]8317960', '0']]
Level 2 : [[17793, '425[]83', '1'], [25490, '17960', '0']]
Level 3 : [[16383, ' ', '1'], [16383, ',', '0'], [25490, '17960', '0']]
Level 4 : [[12677, '1', '1'], [12813, '7960', '0'], [16383, ',', '0']]
Level 5 : [[7915, '42', '1'], [9878, '5[]83', '0'], [12813, '7960', '0'], [16383, ',', '0']]
Level 6 : [[6139, '79', '1'], [6674, '60', '0'], [9878, '5[]83', '0'], [16383, ' ', '1']]
Level 7 : [[4069, '5', '1'], [5809, '[]83', '0'], [6674, '60', '0'], [12677, '1', '1'], [16383, ',', '0']]
Level 8 : [[3950, '4', '1'], [3965, '2', '0'], [5809, '[]83', '0'], [6674, '60', '0'], [16383, ' ', '1']]
Level 9 : [[3141, '6', '1'], [3533, '0', '0'], [3965, '2', '0'], [5809, '[]83', '0'], [12677, '1', '1'], [16383, ',', '0']]
Level 10 : [[3021, '7', '1'], [3118, '9', '0'], [3533, '0', '0'], [3965, '2', '0'], [5809, '[]83', '0'], [16383, ' ', '1']]
Level 11 : [[2810, '[]8', '1'], [2999, '3', '0'], [3118

In [6]:
letter_binary = []
if len(only_letters) == 1:
    lettercode = [only_letters[0], "0"]
    letter_binary.append(letter_code*len(my_string))
else:
    for letter in only_letters:
        code =""
        for node in checklist:
            if len (node)>2 and letter in node[1]:           #genrating binary code
                code = code + node[2]
        lettercode =[letter,code]
        letter_binary.append(lettercode)
print(letter_binary)
print("Binary code generated:")
for letter in letter_binary:
    print(letter[0], letter[1])

[['[', '0100111'], ['0', '00000'], [',', '10'], [' ', '11'], ['1', '001'], ['4', '0111'], ['2', '0110'], ['5', '0101'], [']', '0100110'], ['8', '010010'], ['3', '01000'], ['7', '00011'], ['6', '00001'], ['9', '00010']]
Binary code generated:
[ 0100111
0 00000
, 10
  11
1 001
4 0111
2 0110
5 0101
] 0100110
8 010010
3 01000
7 00011
6 00001
9 00010


In [7]:
bitstring =""
for character in my_string:
    for item in letter_binary:
        if character in item:
            bitstring = bitstring + item[1]
binary ="0b"+bitstring


In [8]:

bitstring =""
for character in my_string:
    for item in letter_binary:
        if character in item:
            bitstring = bitstring + item[1]
binary ="0b"+bitstring

                                        # binary code generated

uncompressed_file_size = len(my_string)*7
compressed_file_size = len(binary)-2


In [9]:

bitstring = str(binary[2:])
uncompressed_string =""
code =""
for digit in bitstring:
    code = code+digit
    pos=0                                        #iterating and decoding
    for letter in letter_binary:
        if code ==letter[1]:
            uncompressed_string=uncompressed_string+letter_binary[pos] [0]
            code=""
        pos+=1

In [10]:


temp = re.findall(r'\d+', uncompressed_string)
res = list(map(int, temp))
res = np.array(res)
res = res.astype(np.uint8)
res = np.reshape(res, shape)
print(res)
data = Image.fromarray(res)
data.save('huffman_compressed.png')
if a.all() == res.all():
    print("Success")

[[  0   1   0 ...   0   0   1]
 [  2  85 124 ... 101  68   0]
 [  0 120 176 ... 114  47   0]
 ...
 [  0  42  64 ...  64  43   0]
 [  1  29  43 ...  42  35   0]
 [  0   0   1 ...   0   1   0]]
Success
